modLoader="javafml"
loaderVersion="[37,)"
license="Academic Free License v3.0"

[[mods]]
modId="kobolds"
version="1.0.0"
displayName="Kobolds"
credits="Muffins"
displayURL="Cupcakes"
authors="Jusey1"

[[dependencies.kobolds]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1]"
    ordering="NONE"
    side="BOTH"




